import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import newsection from "@/styles/New.module.css";
import herosection from "@/styles/Hero.module.css";
import brands from "@/styles/Brands.module.css";
import Productcard from "@/components/Productcard";
import Brands from "@/components/Brands";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>spex.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.herosection}>
        <nav className={herosection.nav}>
          <div className={herosection.menubutton}>
            <button>=</button>
          </div>
          <div className={herosection.logo}>
            <a>spex.</a>
          </div>
          <div className={herosection.navright}>
            <div>a</div>
            <div>b</div>
            <div>cadadaddassd</div>
          </div>
        </nav>
        <div className={herosection.typography}>
          <div className={herosection.typographyleft}>
            <div className={herosection.typographyleftcontent}>
              <div className={herosection.herotitle}>
                GALLERY<br></br>&nbsp;&nbsp;&nbsp;OPTICIAN
              </div>
            </div>
            <div className={herosection.typographyleftcontent}>
              Wide range of sunglasses<br></br> and frames from world brands
            </div>
            <button className={herosection.typographyleftcontent}>
              CATALOG &nbsp;⟶
            </button>
          </div>
          <div className={herosection.scrolldown}> SCROLL DOWN ⟶ </div>
        </div>
      </section>
      <section className={styles.newsection}>
        <div className={styles.title}>
          WHAT&apos;S NEW
          <a className={styles.explore} href="#">
            VIEW MORE ⟶{" "}
          </a>
        </div>
        <div className={newsection.new}>
          <Productcard />
          <Productcard />
          <Productcard />
        </div>
      </section>
      <section className={styles.brandssection}>
        <div className={styles.title}>BRANDS</div>
        <Brands />
        <a className={styles.explore} href="#">
          ALL BRANDS ⟶{" "}
        </a>
      </section>

      <section className={styles.collectionsection}>
        <div className={styles.title}>COLLECTION</div>
      </section>
      <section className={styles.findussection}></section>
      <section className={styles.instagramsection}></section>
      <footer>asdasd</footer>
    </>
  );
}
