import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import newsection from "@/styles/New.module.css";
import herosection from "@/styles/Hero.module.css";
import collectionsection from "@/styles/Collections.module.css";
import findussection from "@/styles/Findus.module.css";
import instagramsection from "@/styles/Instagram.module.css";
import footersection from "@/styles/Footer.module.css";

import Productcard from "@/components/Productcard";
import Brands from "@/components/Brands";
import Collectioncard from "@/components/Collectioncard";

export default function Home() {
  return (
    <>
      <Head>
        <title>spex.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.herosection}>
        <nav className={herosection.nav}>
          <div className={herosection.menubutton}>
            <button>=</button>
          </div>
          <div className={herosection.logo}>
            <a>spex.</a>
          </div>

          <div>
            <a>
              <img src="assets/icons/search.png" alt=""></img>
            </a>
          </div>
          <div>
            <a>
              <img src="assets/icons/heart.png" alt=""></img>
            </a>
          </div>
          <div>
            <a>
              <img src="assets/icons/shop.png" alt=""></img>
            </a>
          </div>
          <div>
            <a>Log In</a>
          </div>
        </nav>
        <div className={herosection.typography}>
          <div className={herosection.typographyleft}>
            <div className={herosection.typographyleftcontent}>
              <div className={herosection.herotitle}>
                GALLERY<br></br>&nbsp;&nbsp;&nbsp;OPTICIAN
              </div>
            </div>
            <div className={herosection.typographyleftcontent}>
              Wide range of sunglasses<br></br> and frames from world brands
            </div>
            <button className={herosection.typographyleftcontent}>
              CATALOG &nbsp;⟶
            </button>
          </div>
          <div className={herosection.scrolldown}> SCROLL DOWN ⟶ </div>
        </div>
      </section>
      <section className={styles.newsection}>
        <div className={styles.title}>
          WHAT&apos;S NEW
          <a className={styles.explore} href="#">
            VIEW MORE ⟶{" "}
          </a>
        </div>
        <div className={newsection.new}>
          <Productcard number="1" />
          <Productcard number="2" />
          <Productcard number="3" />
        </div>
      </section>
      <section className={styles.brandssection}>
        <div className={styles.title}>BRANDS</div>
        <Brands />
        <a className={styles.explore} href="#">
          ALL BRANDS ⟶{" "}
        </a>
      </section>

      <section className={styles.collectionsection}>
        <div className={styles.title}>COLLECTION</div>
        <div className={collectionsection.collections}>
          <Collectioncard number="1" />
          <Collectioncard number="2" />
          <Collectioncard number="3" />
        </div>
        <div className={collectionsection.drag}>DRAG TO SEE MORE</div>
      </section>
      <section className={styles.findussection}>
        <div>
          <img src="assets/shelf.jpg"></img>
        </div>
        <div className={styles.title}>
          <div>
            HOW TO
            <br></br>
            &nbsp;&nbsp;&nbsp;FIND US
          </div>
          <div className={findussection.buttons}>
            <button>
              <span>KIEV</span>
              <span>⟶</span>
            </button>
            <button>
              <span>ODESSA</span>
              <span>⟶</span>
            </button>
            <button>
              <span>KHARKIV</span>
              <span>⟶</span>
            </button>
            <button>
              <span>DNIPRO</span>
              <span>⟶</span>
            </button>
          </div>
        </div>
      </section>

      <section className={styles.instagramsection}>
        <div className={styles.title}>INSTAGRAM</div>
        <div className={instagramsection.images}>
          <div>
            <img src="assets/in2.jpg" alt="image"></img>
          </div>
          <div>
            <img src="assets/in1.jpg" alt="image"></img>
          </div>
          <div>
            <img src="assets/in3.jpg" alt="image"></img>
          </div>
        </div>
        <a className={styles.explore} href="#">
          INSTAGRAM ⟶{" "}
        </a>
      </section>
      <footer className={styles.footersection}>
        <div className={footersection.footer}>
          <div className={footersection.flex}>
            <div className={footersection.logo}>spex.</div>
            <div>c 2021 spex</div>
          </div>
          <div className={footersection.flex}>
            <div className={footersection.title}>ABOUT US</div>
            <div>
              <a>SHOPS</a>
            </div>
            <div>
              <a>VACANCIES</a>
            </div>
            <div>
              <a>STERMS OF USE</a>
            </div>
          </div>
          <div className={footersection.flex}>
            <div className={footersection.title}>SERVICES</div>
            <div>
              <a>PAYMENT AND DELIVERY</a>
            </div>
            <div>
              <a>RETURN AND EXCHANGE</a>
            </div>
            <div>
              <a>FAQ</a>
            </div>
            <div>
              <a>CONTACTS</a>
            </div>
            <div>
              <a>HELP</a>
            </div>
          </div>
          <div className={footersection.flex}>
            <div className={footersection.title}>
              LEARN ABOUT SPECIAL OFFERS
            </div>
            <div className={footersection.form}>
              <form>
                <input type="email" placeholder="Email"></input>
                <button type="submit">OK</button>
              </form>
            </div>
            <div className={footersection.medias}>a b c</div>
          </div>
        </div>
      </footer>
    </>
  );
}
